### ISSUE TITLE
[attributes] Attribute package roadmap

### ISSUE THREAD

**Issue by SerafimArts** [spiral/framework#351]
## Implemented

- [x] Interface implementation
- [x] Doctrine reader implementation
  - [x] Exception wrapping
- [x] PHP 8.0 reader implementation
- [x] PHP 7.x polyfill reader implementation
  - **Reading**
    - [x] Class (`#[Attr] class ClassName { ... }`)
    - [ ] Anonymous class (`new #[Attr] class { ... }`)
    - [x] Class constant (`#[Attr] public const CONSTANT = ...;`)
    - [x] Property (`#[Attr] public $property = ...;`)
    - [x] Function (`#[Attr] function func() { ... }`)
    - [x] Function parameter (`function func(#[Attr] $param) { ... }`)
    - [x] Method (`#[Attr] public function method() { ... }`)
    - [x] Method parameter (`public function method(#[Attr] $param) { ... }`)
    - [x] Closure (`$fn = #[Attr] function() { ... }`)
    - [x] Closure parameter (`$fn= function(#[Attr] $param) { ... }`)
    - [x] Arrow function (`$fn = #[Attr] fn() => ...`)
    - [x] Arrow function parameter (`$fn = fn(#[Attr] $param) => ...`)
  - **Syntax/Semantic**
    - [x] General syntax errors
    - [x] Missing attribute class
    - [ ] Context validation (cheking `Attribute::TARGET_*` flag value)
    - [ ] Count validation (checking `Attribute::IS_REPEATABLE` flag value)
    - [x] Named arguments
      - [x] Exceptions (named arguments can only be at the end)
    - [x] Evaluation constant expressions
      - [x] Magic constants (e.g. `__FILE__`, `__LINE__`, etc)
      - [x] Exceptions (non-constant expression)
- **Combining algorithms**
  - [x] Merge metadata (i.e. attributes and annotations) when reading
  - [x] Getting metadata from the first available reader
  - [ ] Merge based on uniqueness of attribute names
- **Attribute instantiation**
 - [x] Doctrine instantiation (fill properties or pass all attribute arguments to the constructor)
   - [x] Invalid field exception
   - [x] Number of constructor arguments mismatch exception
   - [x] Constructor argument type mismatch exception
 - [x] Named arguments (see also: [Doctrine\Common\Annotations\NamedArgumentConstructorAnnotation](https://github.com/doctrine/annotations/blob/1.12.x/lib/Doctrine/Common/Annotations/NamedArgumentConstructorAnnotation.php))
    - [x] Invalid named argument exception
    - [x] Replace to attribute (mark as deprecated)
- [x] PSR-16 support

## Available Implementation

Repository: https://github.com/spiral/attributes

Installation (for testing):
```sh
$ composer require spiral/attributes
```

**Comment by SerafimArts** [comment]
Merged in https://github.com/spiral/framework/pull/405

The missing functionality will be implemented in a separate PR/issue.
